# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-20 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='blocks',
        ),
        migrations.AlterField(
            model_name='block',
            name='_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='previousHash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='blockchain.Transaction'),
        ),
        migrations.DeleteModel(
            name='Chain',
        ),
    ]
