# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-20 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20181020_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='blockchain.pendingTransactions'),
        ),
    ]
