# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20181020_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='blockchain.Transaction'),
        ),
    ]
